version: "3"
services:
  app:
    image: "${REPOSITORY_URI}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - "MF_USERNAME=${MF_USERNAME}"
     - "MF_PASS=${MF_PASS}"

